Revert "Add backwards-compatibility for older webapp"
This reverts commit e86a882ea438637e9336e3b2e5de288b1b769a65.

One of these commits causes a 500 for all pages in production:

	AttributeError: type object 'object' has no attribute 'facebook_app_id'