Retry upload-images.sh on failure. (#186)
## Summary:
The update-devserver-static-images job periodically (regularly,
but unpredictably) fails with:
> ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF

I have been unable to figure out why.  Until that's figured out, let's
just retry.  I'm hoping it's rare enough we can get through this,
eventually, if we retry enough.

Issue: https://jenkins.khanacademy.org/job/misc/job/update-devserver-static-images/130/execution/node/196/log/

## Test plan:
Will run it on jenkins

Author: csilvers

Reviewers: #infra-platform, dbraley, jenglund

Required Reviewers:

Approved By:

Checks:

Pull Request URL: https://github.com/Khan/jenkins-jobs/pull/186