Add a weekly script to clean invalid branches on jenkins.
Summary:
Historically we've got a lot of messages like these when running
jenkins jobs:
```
error: refs/heads/multiple-topic-trees does not point to a valid object!
```

I found a magic script that gets rid of those!, at
    http://stackoverflow.com/questions/6265502/getting-rid-of-does-not-point-to-a-valid-object-for-an-old-git-branch

I cleaned up the script and now we run it weekly on every repo on
jenkins.

I still don't know what //causes// this to happen in the first place,
but I don't care that much as long as we can clean it up.

Oops, forgot to rename `$f` to `$ref` in one place.

The original code I was cribbing from called its refs `$f` for some
strange reason.  I changed it...mostly.

Test Plan:
I ran the inner loop (after the cd) manually on my local machine,
without error.  (But without actually cleaning anything up either.)

(None new)

Reviewers: chris

Reviewed By: chris

Differential Revision: https://phabricator.khanacademy.org/D31782