Revert "Substate alertlib"
This reverts commit 6f1998d5556dfa3dde68716c9b696233480b5093.

One of these commits causes a 500 for all pages in production:

	AttributeError: type object 'object' has no attribute 'facebook_app_id'