Revert "Change how jenkins handles secrets, and update for the new location of secrets"
This reverts commit 0dc67d195f3027b3cf269f3dc0c1a8dcfa1c2ad6.

One of these commits causes a 500 for all pages in production:

	AttributeError: type object 'object' has no attribute 'facebook_app_id'